version: '3.7'
services:
  reverse-proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  webapp:
    image: zachariahouache/xyzapp
    container_name: webapp
